version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - backend

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        networks:
            - dbnet
        ports:
            - 8080:80
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - "dbdata:/var/lib/postgresql/data"
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=rss_reader
        networks:
            - dbnet

networks:
    dbnet:

volumes:
    dbdata:
