  
version: "3.8"

services:
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: rss_reader
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    dbdata:
